#cloud-config
hostname: plural-{{ trunc 10 .MachineID }}

users:
  - name: @USERNAME@
    passwd: @PASSWORD@
    groups: [ "admin" ]

write_files:
  - path: /etc/rancher/k3s/registries.yaml
    permissions: "0644"
    content: |
      mirrors:
        "*":
  - path: /etc/plural-id
    permissions: "0644"
    content: |
      {{ uuidv4 }}

k3s:
  enabled: true
  replace_args: true
  args:
    - --node-name=plural
    - --embedded-registry
    - --disable=traefik,servicelb

bundles:
  - targets:
      - run:///plural-bundle.tar
    local_file: true
  - targets:
      - run:///plural-images-bundle.tar
    local_file: true
  - targets:
      - run:///plural-trust-manager-bundle.tar
    local_file: true
  - targets:
      - run://quay.io/kairos/community-bundles:system-upgrade-controller_latest

plural:
  token: @TOKEN@
  url: @URL@