#cloud-config
hostname: plural-{{ trunc 10 .MachineID }}

users:
  - name: @USERNAME@
    passwd: @PASSWORD@
    groups: [ "admin" ]

stages:
  boot:
    - name: Enable wireless
      commands:
        - connmanctl enable wifi
        - wpa_passphrase '@WIFISSID@' '@WIFIPASSWORD@' > /etc/wpa_supplicant/wpa_supplicant.conf
        - wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
        - udhcpc -i wlan0 &

write_files:
  - path: /etc/rancher/k3s/registries.yaml
    permissions: "0644"
    content: |
      mirrors:
        "*":
# TODO: Enable once it will be fixed.
#  - path: /etc/plural-id
#    permissions: "0644"
#    content: |
#      {{ uuidv4 }}

k3s:
  enabled: true
  replace_args: true
  args:
    - --node-name=plural-{{ trunc 10 .MachineID }}
    - --embedded-registry
    - --disable=traefik,servicelb

bundles:
  - targets:
      - run:///plural-bundle.tar
    local_file: true
  - targets:
      - run:///plural-images-bundle.tar
    local_file: true
  - targets:
      - run:///plural-trust-manager-bundle.tar
    local_file: true

plural:
  token: @TOKEN@
  url: @URL@