#cloud-config

hostname: metal-{{ trunc 4 .MachineID }}

users:
  - name: "kairos"                       # The username for the user.
    passwd: "kairos"
    groups: [ "admin" ]

k3s:
  enabled: true
  replace_args: true
  args:
    - --node-name=kairos

boot:
  - name: "Init"
    commands:
      - sudo chmod 755 /etc/rancher/k3s/k3s.yaml
      - mkdir -p ~/.kube
      - k3s kubectl config view --raw > $HOME/.kube/config