hostname: metal-{{ trunc 4 .MachineID }}
users:
  - name: kairos
    passwd: kairos
#    ssh_authorized_keys:
#     - github:mudler

boot:
  - name: "Hello world"
    commands:
      - |
        echo "Hello world!"