hostname: metal-{{ trunc 4 .MachineID }}
users:
  - name: kairos
    passwd: kairos
#    ssh_authorized_keys:
#     - github:mudler

k3s:
  enabled: true
  args:
    - --disable=traefik,servicelb

boot:
  - name: "Hello world"
    commands:
      - |
        echo "Hello world!"