#plural-config
# TODO: Write renovate config to keep it up to date.
image: quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1
aurorabootImage: quay.io/kairos/auroraboot:v0.4.3
craneImage: gcr.io/go-containerregistry/crane:latest
bundles:
  plural-bundle: ghcr.io/pluralsh/kairos-plural-bundle:0.1.6
  plural-images-bundle: ghcr.io/pluralsh/kairos-plural-images-bundle:0.1.2
  plural-trust-manager-bundle: ghcr.io/pluralsh/kairos-plural-trust-manager-bundle:0.1.0