image: quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1
# renovate: datasource=docker packageName=ghcr.io/pluralsh/auroraboot versioning=docker
aurorabootImage: ghcr.io/pluralsh/auroraboot:v0.4.3
craneImage: gcr.io/go-containerregistry/crane:latest
bundles:
  # renovate: datasource=docker packageName=ghcr.io/pluralsh/kairos-plural-bundle versioning=docker
  plural-bundle: ghcr.io/pluralsh/kairos-plural-bundle:1.0.0
  # renovate: datasource=docker packageName=ghcr.io/pluralsh/kairos-plural-images-bundle versioning=docker
  plural-images-bundle: ghcr.io/pluralsh/kairos-plural-images-bundle:1.0.0
  # renovate: datasource=docker packageName=ghcr.io/pluralsh/kairos-plural-trust-manager-bundle versioning=docker
  plural-trust-manager-bundle: ghcr.io/pluralsh/kairos-plural-trust-manager-bundle:0.2.0
