#cloud-config
hostname: plural-edge-{{ trunc 10 .MachineID }}
users:
  - name: "kairos"
    passwd: @PASSWORD@
    groups: [ "admin" ]
k3s:
  enabled: true
  replace_args: true
  args:
    - --node-name=kairos
    - --embedded-registry
    - --disable=traefik,servicelb
bundles:
  - targets:
      - run:///usr/local/bundles/plural-bundle.tar
    local_file: true
  - targets:
      - run:///usr/local/bundles/plural-images-bundle.tar
    local_file: true
plural:
  token: @TOKEN@
  url: @URL@