#!/bin/bash

set -e

IMAGE=quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1

case "$(uname)" in
  Linux) BS=10MB ;;
  Darwin) BS=10m ;;
esac

templ() {
    local file="$3"
    local value="$2"
    local sentinel="$1"
    sed -i "s/@${sentinel}@/$(echo "${value}" | sed -e 's/[&\\/]/\\&/g; s/$/\\/' -e '$s/\\$//')/g" "${file}"
}

read -p "Please enter your Plural Console URL: " -r URL
read -p "Please enter your Plural Console token: " -rs TOKEN
echo -e ""
read -p "Please enter password for kairos user: " -rs PASSWORD
echo -e ""

echo "Downloading cloud-config.yaml..."
curl --silent https://raw.githubusercontent.com/pluralsh/edge/main/hack/cloud-config.yaml -o cloud-config.yaml

echo "Templating cloud-config.yaml..."
templ "URL" "${URL}" cloud-config.yaml
templ "TOKEN" "${TOKEN}" cloud-config.yaml
templ "PASSWORD" "${PASSWORD}" cloud-config.yaml

echo "Creating build directory..."
mkdir -p build

echo "Preparing image..."
mkdir -p image
docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$PWD"/image:/image \
  -v "$PWD"/prepare-image.sh:/prepare-image.sh \
  -e IMAGE=$IMAGE \
  --privileged -ti --rm \
  --entrypoint=/prepare-image.sh quay.io/kairos/auroraboot:v0.4.3

echo "Building image..."
mkdir -p build
docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$PWD"/build:/tmp/build \
  -v "$PWD"/image:/tmp/image \
  -v "$PWD"/cloud-config.yaml:/cloud-config.yaml \
  --privileged -ti --rm \
  --entrypoint=/build-arm-image.sh quay.io/kairos/auroraboot:v0.4.3 \
  --model rpi4 \
  --state-partition-size 6200 \
  --recovery-partition-size 4200 \
  --size 15200 \
  --images-size 2000 \
  --directory /tmp/image \
  --config /cloud-config.yaml \
  --docker-image $IMAGE /tmp/build/kairos.img

echo "Successfully generated image and saved it to build directory.
Now you can flash your storage device and conect it to your Raspberry Pi 4.
Flashing can be done with:

sudo dd if build/kairos.img of=<DEVICE_PATH> oflag=sync status=progress bs=$BS

<DEVICE_PATH> needs to be replaced with path of your storage device, i.e. /dev/rdisk4"