#!/bin/bash

set -e

IMAGE=quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1
CLOUD_CONFIG=cloud-config.yaml
SKIP_TEMPLATING=n

case "$(uname)" in
  Linux) BS=10MB ;;
  Darwin) BS=10m ;;
esac

templ() {
    local file="$3"
    local value="$2"
    local sentinel="$1"
    sed -i "s/@${sentinel}@/$(echo "${value}" | sed -e 's/[&\\/]/\\&/g; s/$/\\/' -e '$s/\\$//')/g" "${file}"
}

if [ -f $CLOUD_CONFIG ]; then
  read -p "Configuration file $CLOUD_CONFIG already exists. Would you like to skip templating and use it? (y/n) " -r SKIP_TEMPLATING
fi

if [ "$SKIP_TEMPLATING" == "${SKIP_TEMPLATING#[Yy]}" ] ;then
  read -p "Please enter your Plural Console URL: " -r URL
  read -p "Please enter your Plural Console token: " -rs TOKEN
  echo -e ""
  read -p "Please enter password for kairos user: " -rs PASSWORD
  echo -e ""

  echo "Downloading cloud-config.yaml..."
  curl --silent https://raw.githubusercontent.com/pluralsh/edge/main/hack/cloud-config.yaml -o cloud-config.yaml

  echo "Templating cloud-config.yaml..."
  templ "URL" "${URL}" cloud-config.yaml
  templ "TOKEN" "${TOKEN}" cloud-config.yaml
  templ "PASSWORD" "${PASSWORD}" cloud-config.yaml
fi

echo "Building image..."
curl --silent https://raw.githubusercontent.com/pluralsh/edge/main/hack/build-arm-image.sh -o build-arm-image.sh
chmod +x build-arm-image.sh
mkdir -p build

docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$PWD"/build:/tmp/build \
  -v "$PWD"/cloud-config.yaml:/cloud-config.yaml \
  -v "$PWD"/build-arm-image.sh:/build-arm-image.sh \
  --privileged -ti --rm \
  --entrypoint=/build-arm-image.sh quay.io/kairos/auroraboot:v0.4.3 \
  --model rpi4 \
  --docker-image "${IMAGE}" \
  --config /cloud-config.yaml /tmp/build/kairos.img

echo "Successfully generated image and saved it to build directory.
Now you can flash your storage device and conect it to your Raspberry Pi 4.
Flashing can be done with:

sudo dd if=build/kairos.img of=<DEVICE_PATH> oflag=sync status=progress bs=$BS

<DEVICE_PATH> needs to be replaced with path of your storage device, i.e. /dev/rdisk4"