apiVersion: v1
kind: ServiceAccount
metadata:
  name: plural-join
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plural-join
subjects:
  - kind: ServiceAccount
    name: plural-join
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: plural-join
  namespace: default
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-k8s-api
          image: alpine/curl:8.10.0
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Kubernetes API server to be ready..."
              until curl --silent --fail --max-time 5 --insecure -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default/readyz; do
                echo "API server is not ready, retrying in 5 seconds..."
                sleep 5
              done
              echo "Kubernetes API server is ready!"
      containers:
        - name: plural-cloud
          image: "@BASE_IMAGE@"
          args: ["edge", "bootstrap", "--machine-id", "@MACHINE_ID@"]
          env:
            - name: PLURAL_CONSOLE_TOKEN
              value: "@TOKEN@"
            - name: PLURAL_CONSOLE_URL
              value: "@URL@"
      restartPolicy: Never
      serviceAccountName: plural-join
