#!/bin/bash -i

IMAGE=quay.io/kairos/alpine:3.19-standard-arm64-rpi4-v3.2.4-k3sv1.31.3-k3s1

case "$(uname)" in
  Linux) BS=10MB ;;
  Darwin) BS=10m ;;
esac

templ() {
    local file="$3"
    local value="$2"
    local sentinel="$1"
    sed -i "s/@${sentinel}@/$(echo "${value}" | sed -e 's/[&\\/]/\\&/g; s/$/\\/' -e '$s/\\$//')/g" "${file}"
}

read -p "Please enter your Plural Console URL: " -r URL
read -p "Please enter your Plural Console token: " -rs TOKEN
echo -e "\n"
read -p "Please enter password for kairos user: " -rs PASSWORD
echo -e "\n"

curl --silent https://raw.githubusercontent.com/pluralsh/edge/main/cloud-config.yaml -o cloud-config.yaml

templ "URL" "${URL}" cloud-config.yaml
templ "TOKEN" "${TOKEN}" cloud-config.yaml
templ "PASSWORD" "${PASSWORD}" cloud-config.yaml

mkdir -p build
docker pull -q $IMAGE
docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$PWD"/build:/tmp \
  -v "$PWD"/cloud-config.yaml:/cloud-config.yaml \
  --privileged -ti --rm \
  --entrypoint=/build-arm-image.sh quay.io/kairos/auroraboot:v0.4.3 \
  --model rpi4 \
  --state-partition-size 6200 \
  --recovery-partition-size 4200 \
  --size 15200 \
  --images-size 2000 \
  --config /cloud-config.yaml \
  --docker-image $IMAGE /tmp/kairos.img

echo "Successfully generated image and saved it to build directory.
Now you can flash your storage device and conect it to your Raspberry Pi 4.
Flashing can be done with:

sudo dd if build/kairos.img of=<DEVICE_PATH> oflag=sync status=progress bs=$BS

<DEVICE_PATH> needs to be replaced witth path of your storage device, i.e. /dev/rdisk4"