name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        image: [ plural-cli, plural-bundle, plural-images-bundle, plural-trust-manager-bundle ]
    name: Build ${{ matrix.image }} image
    runs-on: ubuntu-24.04
    permissions:
      contents: 'read'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v6
        with:
          context: "images/${{ matrix.image }}"
          file: "images/${{ matrix.image }}/Dockerfile"
          push: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_COMMIT=${{ github.sha }}